export const GAME_CONFIG = {
  chunkSize: 16,
  minSquareSize: 3,
  maxSquareSize: 12,
  eventInterval: 10,
  startingRepaints: 2,
  maxRepaints: 3,
  minZoom: 0.25,
  maxZoom: 2.5,
  attackBaseChance: 0.30,
  attackAllySupportBonus: 0.20,
  attackDefenderSupportPenalty: 0.15,
  attackMinChance: 0.10,
  attackMaxChance: 0.95,
  tileSize: 36,
  tileGap: 4,
  tileRadius: 3,
  maxParticles: 160,
  eras: [
    { name: 'ЭРА I — ИСТОК', startTurn: 1, maxIntents: 1 },
    { name: 'ЭРА II — КОНТАКТ', startTurn: 50, maxIntents: 2 },
    { name: 'ЭРА III — РАСКОЛ', startTurn: 100, maxIntents: 3 },
    { name: 'ЭРА IV — ГЛУБОКАЯ ВОЙНА', startTurn: 200, maxIntents: 4 },
  ],
  colors: {
    bg: 0x050706,
    hiddenTile: 0x0a0d0b,
    hiddenTileBorder: 0x172019,
    frontier: 0x26332a,
    species: {
      cyan: { id: 'cyan', name: 'Лазурный Шпиль', shortName: 'Шпиль', title: 'Архитектор', hex: 0x4ad9d0, cssHex: '#4ad9d0', secondaryHex: 0x91fff6, glowHex: 0x2ca49d, passiveName: 'СТРУКТУРНАЯ ПАМЯТЬ', passiveDesc: 'Клетки, укреплённые квадратом, получают дополнительную защиту.' },
      coral: { id: 'coral', name: 'Коралловый Цвет', shortName: 'Коралл', title: 'Хищник', hex: 0xff655f, cssHex: '#ff655f', secondaryHex: 0xff918d, glowHex: 0xd64742, passiveName: 'ПИР', passiveDesc: 'Первая атака за ход по слабо защищённой цели получает небольшой бонус.' },
      yellow: { id: 'yellow', name: 'Солнечная Вспышка', shortName: 'Солнце', title: 'Исследователь', hex: 0xf4bd52, cssHex: '#f4bd52', secondaryHex: 0xffd986, glowHex: 0xc38e29, passiveName: 'ЧУТЬЁ', passiveDesc: 'Каждый третий ход прогноз одной соседней клетки становится значительно точнее.' },
      magenta: { id: 'magenta', name: 'Бархатный Пульс', shortName: 'Бархат', title: 'Паразит', hex: 0xe95a9e, cssHex: '#e95a9e', secondaryHex: 0xff96c7, glowHex: 0xbd3978, passiveName: 'ПРИВИВКА', passiveDesc: 'Перекрашенная клетка сразу участвует в замыкании квадратов и получает укрепление.' },
      violet: { id: 'violet', name: 'Лотос Пустоты', shortName: 'Лотос', title: 'Крепость', hex: 0x9375d8, cssHex: '#9375d8', secondaryHex: 0xbba5ee, glowHex: 0x6749ad, passiveName: 'УКОРЕНЕНИЕ', passiveDesc: 'Клетки рядом с Ядром считаются укреплёнными.' },
    },
  },
} as const;

export type SpeciesId = 'cyan' | 'coral' | 'yellow' | 'magenta' | 'violet';
